[project]
name = "slipperysupernova"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "slipperysupernova", email = "slipperysupernova@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.14.0",
]

[tool.maturin]
module-name = "slipperysupernova._core"
python-packages = ["slipperysupernova"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
